name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: dependencies
      run: |
         sudo apt-get install -y build-essential libgtest-dev
         sudo apt-get install -y g++ make
    - name: make
      run: make
    - name: chmod
      run: chmod +x ./tests
    - name: clean
      run: make clean
